# What are the top 5 brands by receipts scanned among users 21 and over?
	
with COMBINED_DATA as (
	SELECT T.RECEIPT_ID, 
		T.USER_ID,
		P.BRAND,  
		CAST(U.BIRTH_DATE AS DATETIME) AS BIRTH_DATE,
		DATE(BIRTH_DATE,'+21  year' ) <= DATE('now') AS OVER_21
	FROM TRANSACTION_TAKEHOME T
		LEFT JOIN PRODUCTS_TAKEHOME P ON T.BARCODE=P.BARCODE
		LEFT JOIN USER_TAKEHOME U ON T.USER_ID=U.ID
	), 
	SCANS_BY_RECEIPTS AS (
		SELECT BRAND, 
                                  COUNT(DISTINCT RECEIPT_ID) AS RECEIPTS_SCANNED
		FROM COMBINED_DATA                
		WHERE OVER_21 IS TRUE
		GROUP BY BRAND
		ORDER BY RECEIPTS_SCANNED DESC
		)
	SELECT BRAND
	FROM SCANS_BY_RECEIPTS 
             WHERE BRAND IS NOT NULL AND BRAND NOT IN ('')
             LIMIT 5


# Which is the leading brand in the Dips & Salsa category?
# Let us assume that we are calculating leading brand by number of times the brand appears in the receipts.

with COMBINED_DATA as (
	SELECT  P.BRAND, 
		    COUNT(DISTINCT(RECEIPT_ID)) AS TOTAL_OCCURANCES 
	FROM TRANSACTION_TAKEHOME T
		LEFT JOIN PRODUCTS_TAKEHOME P ON T.BARCODE=P.BARCODE
		LEFT JOIN USER_TAKEHOME U ON T.USER_ID=U.ID
	WHERE CATEGORY_2= 'Dips & Salsa'
	GROUP BY 1
	ORDER BY TOTAL_OCCURANCES DESC
	)
	
	SELECT BRAND
	FROM COMBINED_DATA
 WHERE BRAND IS NOT NULL AND BRAND NOT IN ('')
	LIMIT 1




# What are the top 5 brands by sales among users that have had their account for at least six months?

with COMBINED_DATA as (
	SELECT T.RECEIPT_ID, 
		  T.USER_ID,
		  P.BRAND,  
		  CAST(U.CREATED_DATE AS DATETIME) AS CREATED_DATE,
		  DATE(CREATED_DATE,'+ 6 MONTH' ) <= DATE('now') AS ACCOUNT_SIX_MONTH_OLD,
		  CAST(FINAL_SALE AS DECIMAL) FINAL_SALE
	FROM TRANSACTION_TAKEHOME T
	    LEFT JOIN PRODUCTS_TAKEHOME P ON T.BARCODE=P.BARCODE
                 LEFT JOIN USER_TAKEHOME U ON T.USER_ID=U.ID
             ),
	
	FINAL AS (
		SELECT BRAND, SUM(FINAL_SALE) TOTAL_SALES
		FROM COMBINED_DATA
		WHERE ACCOUNT_SIX_MONTH_OLD IS TRUE
		GROUP BY BRAND
		ORDER BY  TOTAL_SALES DESC
		)
	SELECT BRAND
	FROM FINAL
             LIMIT 5
